### ISSUE TITLE
Header file inclusion

### ISSUE THREAD

**Issue by ciscoski** [IARSystems/ewptool#50]
Is there a way to let the tool add also header files to the project?

Thanks
FC

**Comment by felipe-iar** [comment]
Hi @ciscoski,

Such feature is not available as per EWPtool 4.2.6.

Though it is a nice suggestion, hence I added it as feature request for a future version.

Stay tuned. Thanks.

**Comment by felipe-iar** [comment]
Hi @ciscoski 

We added it as an optional feature in EWPtool 4.2.7 which should cover your and similar use cases.
You can find more information in the [Release Notes for EWPtool 4.2.7](https://github.com/IARSystems/ewptool/releases/tag/4.2.7).

Please enjoy and let us know.

**Comment by ciscoski** [comment]
That is much appriciate.
Thanks
